# Generated by Django 4.2.7 on 2026-04-24 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Binance 거래 페어 (예: BTCUSDT)', max_length=20, unique=True, verbose_name='심볼')),
                ('name', models.CharField(help_text='코인 전체 이름 (예: Bitcoin)', max_length=100, verbose_name='코인명')),
                ('is_active', models.BooleanField(default=True, help_text='가격 수집 활성화 여부', verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '코인',
                'verbose_name_plural': '코인 목록',
                'db_table': 'coins_coin',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='현재가 (USDT)')),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='24시간 거래량')),
                ('change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='24시간 등락률 (%)')),
                ('high_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='24시간 최고가')),
                ('low_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='24시간 최저가')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='수집 시각')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='coins.coin', verbose_name='코인')),
            ],
            options={
                'verbose_name': '코인 가격',
                'verbose_name_plural': '코인 가격 내역',
                'db_table': 'coins_coinprice',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['coin', '-timestamp'], name='coins_coinp_coin_id_29a06a_idx'), models.Index(fields=['-timestamp'], name='coins_coinp_timesta_edde91_idx')],
            },
        ),
    ]
