# Generated by Django 4.2.7 on 2026-04-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', '이상 (목표가 이상)'), ('below', '이하 (목표가 이하)')], help_text='above: 목표가 초과 시 알림 / below: 목표가 미만 시 알림', max_length=10, verbose_name='조건')),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='목표가 (USDT)')),
                ('is_active', models.BooleanField(default=True, help_text='비활성화 시 조건 체크 제외', verbose_name='활성화')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 트리거 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='coins.coin', verbose_name='코인')),
            ],
            options={
                'verbose_name': '가격 알림',
                'verbose_name_plural': '가격 알림 목록',
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='알림 발동 시 자동 생성된 메시지', verbose_name='알림 메시지')),
                ('ai_analysis', models.TextField(blank=True, default='', help_text='EXAONE 3.5가 생성한 시장 분석 텍스트', verbose_name='AI 분석 결과')),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='트리거 발동 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생 시각')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alert', verbose_name='알림')),
            ],
            options={
                'verbose_name': '알림 발동 기록',
                'verbose_name_plural': '알림 발동 기록 목록',
                'db_table': 'alerts_alertlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
